# Generated by Django 2.2.12 on 2020-05-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20191119_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='slug',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Название на английском (для ссылки)'),
        ),
    ]
